apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# declaration of minimum required vendir binary version (optional)
minimumRequiredVersion: 0.8.0

# one or more directories to manage with vendir
directories:
- # path is relative to `vendir` CLI working directory
  path: deps/argocd/vendor

  # set the permissions for this directory (optional; v0.33.0+)
  # by default directories will be created with 0700
  # can be provided as octal, in which case it needs to be prefixed with a `0`
  permissions: 0700

  contents:
  - # path lives relative to directory path # (required)
    path: chart
    
    # skip fetching if the config for this path has not changed since the last sync
    # optional, `false` by default, available since v0.36.0
    # use `vendir sync --lazy=false` to forcefully sync when needed
    lazy: true

    helmChart:
      name: argo-cd
      version: "9.4.7"
      repository:
        url: https://argoproj.github.io/argo-helm


- # path is relative to `vendir` CLI working directory
  path: deps/crossplane/vendor

  # set the permissions for this directory (optional; v0.33.0+)
  # by default directories will be created with 0700
  # can be provided as octal, in which case it needs to be prefixed with a `0`
  permissions: 0700

  contents:
  - # path lives relative to directory path # (required)
    path: chart
    
    # skip fetching if the config for this path has not changed since the last sync
    # optional, `false` by default, available since v0.36.0
    # use `vendir sync --lazy=false` to forcefully sync when needed
    lazy: true

    helmChart:
      name: crossplane
      version: "2.2.0"
      repository:
        url: https://charts.crossplane.io/stable

-
  path: deps/vcluster/vendor

  # set the permissions for this directory (optional; v0.33.0+)
  # by default directories will be created with 0700
  # can be provided as octal, in which case it needs to be prefixed with a `0`
  permissions: 0700

  contents:
  - # path lives relative to directory path # (required)
    path: chart

    # skip fetching if the config for this path has not changed since the last sync
    # optional, `false` by default, available since v0.36.0
    # use `vendir sync --lazy=false` to forcefully sync when needed
    lazy: true

    helmChart:
      name: vcluster
      version: "0.32.1"
      repository:
        url: https://charts.loft.sh

- # path is relative to `vendir` CLI working directory
  path: deps/jsonnet-libs

  # set the permissions for this directory (optional; v0.33.0+)
  # by default directories will be created with 0700
  # can be provided as octal, in which case it needs to be prefixed with a `0`
  permissions: 0700

  contents:
  - # path lives relative to directory path # (required)
    path: docsonnet
    
    # skip fetching if the config for this path has not changed since the last sync
    # optional, `false` by default, available since v0.36.0
    # use `vendir sync --lazy=false` to forcefully sync when needed
    lazy: true

    git:
       # uses git to clone Git repository (optional)
      # http or ssh urls are supported (required)
      url: https://github.com/jsonnet-libs/docsonnet
      # branch, tag, commit; origin is the name of the remote (required)
      # optional if refSelection is specified (available in v0.11.0+)
      ref: origin/master
      # depth of commits to fetch; 0 (default) means everything (optional; v0.29.0+)
      depth: 1
      
      # skip downloading lfs files (optional)
      lfsSkipSmudge: false
      # skip SSL/TLS verification (optional)
      dangerousSkipTLSVerify: false
      # skip initializing any git submodules (optional; v0.28.0+)
      skipInitSubmodules: false

    includePaths:
      - "doc-util/**/*"
    
  - # path lives relative to directory path # (required)
    path: argocd
    
    # skip fetching if the config for this path has not changed since the last sync
    # optional, `false` by default, available since v0.36.0
    # use `vendir sync --lazy=false` to forcefully sync when needed
    lazy: true

    git:
       # uses git to clone Git repository (optional)
      # http or ssh urls are supported (required)
      url: https://github.com/jsonnet-libs/argo-cd-libsonnet
      # branch, tag, commit; origin is the name of the remote (required)
      # optional if refSelection is specified (available in v0.11.0+)
      ref: origin/main
      # depth of commits to fetch; 0 (default) means everything (optional; v0.29.0+)
      depth: 1
      
      # skip downloading lfs files (optional)
      lfsSkipSmudge: false
      # skip SSL/TLS verification (optional)
      dangerousSkipTLSVerify: false
      # skip initializing any git submodules (optional; v0.28.0+)
      skipInitSubmodules: false

    includePaths:
      - "3.1/**/*"
    
    newRootPath: "3.1"